name = "ShaperOriginDesignLib"
uuid = "919415d1-862b-4149-89fa-1b0f92b0b06b"
authors = ["MarkNahabedian <naha@mit.edu> and contributors"]
version = "0.1.1-dev"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
NativeSVG = "5f95e7b2-fe07-4078-b4a7-f744f426795c"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulUS = "7dc9378f-8956-57ef-a780-aa31cc70ff3d"

[compat]
DataStructures = "0.18"
NativeSVG = "0"   # Julia can't parse version designations like "0.1.0-naha"
Unitful = "1"
UnitfulUS = "0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
